apiVersion: v1
kind: Pod
metadata:
  name: prod-clickhouse
  namespace: ${NAMESPACE_CLICKHOUSE}
  labels:
    app: prod-clickhouse
spec:
  nodeSelector:
    env: prod  # This matches the label we created in Task 1
  imagePullSecrets:
    - name: dockerhub-pull
  containers:
    - name: prod-clickhouse
      image: commodore95/quant_data_platform_repository:clickhouse-prod
      imagePullPolicy: IfNotPresent
      env:
        - name: TZ
          value: "Europe/Zurich"
        - name: CLICKHOUSE_USER
          value: "spark"
        - name: CLICKHOUSE_PASSWORD
          value: "sparkpass"
      ports:
        - name: http
          containerPort: 8123
        - name: tcp
          containerPort: 9000
        - name: interserver
          containerPort: 9009
      readinessProbe:
        httpGet:
          path: /ping
          port: 8123
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /ping
          port: 8123
        initialDelaySeconds: 10
        periodSeconds: 10
  restartPolicy: Always
