apiVersion: v1
kind: Service
metadata:
  name: test-schema-registry
  namespace: testenv-avro-schema-registry
spec:
  selector:
    app: test-schema-registry
  ports:
    - name: http
      port: 8081
      targetPort: 8081
