apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dockerhub-token-default
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: quant_data_platform
  config: dev
  managedSecret:
    name: dockerhub-pull
    namespace: default
    type: Opaque
  secrets:
    - DOCKER_HUB_TOKEN