apiVersion: v1
kind: Pod
metadata:
  labels:
    streamlane/role: spark-exec
spec:
  nodeSelector:
    env: test  # This matches the label we created in Task 1
  restartPolicy: Never
  containers:
    - name: spark-kubernetes-executor
      env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "test-kafka-kafka-bootstrap.testenv-kafka:9092"
        - name: KAFKA_STARTING_OFFSETS
          value: "latest"
        - name: KAFKA_TOPIC
          value: "derivatives_tick_market_data"
        - name: SCHEMA_REGISTRY_URL
          value: "http://test-schema-registry.testenv-avro-schema-registry:8081"
        - name: CH_DATABASE
          value: "test_realtime_store"
        - name: CH_TABLE
          value: "derivatives_tick_market_data"
