apiVersion: v1
kind: Pod
metadata:
  labels:
    streamlane/role: spark-exec
spec:
  # Pin executors to your "reserved" Spark node (can be same as driver or different)
  nodeSelector:
    streamlane/role: spark
  restartPolicy: Never
