#cloud-config
runcmd:
  - |
    set -euo pipefail

    K3S_SERVER_URL="https://10.0.0.2:6443"
    K3S_TOKEN="K10f3b6c2c9e7d4c1a2b3c4d5e6f7g8h9i0j::server:abcd1234efgh5678"
    NODE_IP="$(ip -4 route get 10.0.0.2 | awk '{print $7; exit}')"

    curl -sfL https://get.k3s.io | \
      K3S_URL="${K3S_SERVER_URL}" \
      K3S_TOKEN="${K3S_TOKEN}" \
      INSTALL_K3S_EXEC="agent --node-ip ${NODE_IP}" \
      sh -
