apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: ibkr-secret-ib-connector
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: quant_data_platform
  config: dev
  managedSecret:
    name: ibkr-secret
    namespace: ib-connector
    type: Opaque
  secrets:
    - IBKR_USERNAME_1
    - IBKR_PASSWORD_1
    - IBKR_ACCOUNTID_1