apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: test-kafka
spec:
  kafka:
    version: 4.1.0

    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: env
                      operator: In
                      values:
                        - test

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

    config:
      auto.create.topics.enable: "false"
      inter.broker.listener.name: INTERNAL
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1

  entityOperator:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: env
                      operator: In
                      values:
                        - test
    topicOperator: {}
    userOperator: {}

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: test-kafka-all
  labels:
    strimzi.io/cluster: test-kafka
spec:
  replicas: 1
  roles:
    - controller
    - broker
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - test
  storage:
    type: ephemeral
