apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: avro-schema-registry
spec:
  selector:
    app: schema-registry
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
