apiVersion: v1
kind: Service
metadata:
  name: prod-schema-registry
  namespace: prodenv-avro-schema-registry
spec:
  selector:
    app: prod-schema-registry
  ports:
    - name: http
      port: 8081
      targetPort: 8081
